# Generated by Django 4.2.10 on 2024-02-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organistatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
                ('beschrijving', models.CharField(blank=True, max_length=255)),
                ('contactpersoon', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefoonnummer', models.CharField(max_length=64)),
                ('overige_details', models.CharField(max_length=255)),
            ],
        ),
    ]
