# Generated by Django 4.2.10 on 2024-02-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organistatie',
            name='beschrijving',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='organistatie',
            name='overige_details',
            field=models.CharField(max_length=500),
        ),
    ]
