# Generated by Django 4.2.10 on 2024-02-11 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_organistatie_beschrijving_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organistatie',
            new_name='Organisatie',
        ),
        migrations.CreateModel(
            name='Onderzoeken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('avili', models.BooleanField(default=True)),
                ('datef', models.DateField()),
                ('datet', models.DateField()),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('met_belonging', models.BooleanField(default=False)),
                ('organisatie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.organisatie')),
            ],
        ),
    ]
