# Generated by Django 4.2.10 on 2024-02-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_organistatie_organisatie_onderzoeken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onderzoeken',
            name='id',
        ),
        migrations.AddField(
            model_name='onderzoeken',
            name='onderzoek_id',
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='onderzoeken',
            name='datef',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='onderzoeken',
            name='datet',
            field=models.DateField(auto_now=True),
        ),
    ]
