# Generated by Django 4.2.9 on 2024-02-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ervaringsdeskundige', '0008_alter_user_goedegekeurd_door'),
        ('beheerder', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='beheerders',
        ),
    ]
