# Generated by Django 4.2.9 on 2024-02-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beheerder', '0002_customuser_delete_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='functie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
