# Generated by Django 4.2.9 on 2024-02-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beheerder', '0003_customuser_functie'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='achternaam',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='voornaam',
            field=models.CharField(default='', max_length=40),
        ),
    ]
