# Generated by Django 4.2.9 on 2024-02-10 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beheerder', '0004_customuser_achternaam_customuser_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='achternaam',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='voornaam',
        ),
    ]
