# Generated by Django 4.2.10 on 2024-02-14 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('first_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Toezichthouders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ervaringsdeskundige', models.IntegerField(blank=True, null=True)),
                ('voornaam_1', models.TextField()),
                ('achternaam_1', models.TextField()),
                ('telefoonnummer_1', models.TextField()),
                ('voornaam_2', models.TextField(blank=True, null=True)),
                ('achternaam_2', models.TextField(blank=True, null=True)),
                ('telefoonnummer_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Toezichthouders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organisatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
                ('beschrijving', models.CharField(blank=True, max_length=500)),
                ('contactpersoon', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefoonnummer', models.CharField(max_length=64)),
                ('overige_details', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Onderzoeken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('avili', models.BooleanField(default=True)),
                ('datef', models.DateField(auto_now=True)),
                ('datet', models.DateField(auto_now=True)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('met_belonging', models.BooleanField(default=False)),
                ('organisatie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organisatie')),
            ],
        ),
    ]
