# Generated by Django 4.2.9 on 2024-02-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisaties',
            fields=[
                ('organisatie_id', models.AutoField(primary_key=True, serialize=False)),
                ('voornaam', models.TextField(blank=True, null=True)),
                ('achternaam', models.TextField(blank=True, null=True)),
                ('kvk', models.TextField(blank=True, db_column='KVK', null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('beschrijving', models.TextField(blank=True, null=True)),
                ('contact_persoon', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('telefoonnummer', models.IntegerField(blank=True, null=True)),
                ('api_key', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Organisaties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOnderzoek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefonisch', models.BooleanField(blank=True, null=True)),
                ('internet', models.BooleanField(blank=True, null=True)),
                ('locatie', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Type_onderzoek',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Organisaties',
        ),
        migrations.AlterModelOptions(
            name='onderzoeken',
            options={'managed': False},
        ),
    ]
