# Generated by Django 4.2.9 on 2024-02-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_organisaties_typeonderzoek_delete_organisatie_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='onderzoeken',
            table='Onderzoeken',
        ),
    ]
