# Generated by Django 4.2.9 on 2024-02-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_onderzoeken_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deelnames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'Deelnames',
                'managed': False,
            },
        ),
    ]
