# Generated by Django 4.2.10 on 2024-02-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_onderzoeken_id_onderzoeken_onderzoek_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onderzoeken',
            name='onderzoek_id',
        ),
        migrations.AddField(
            model_name='onderzoeken',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
