# Generated by Django 4.2.10 on 2024-02-14 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
        ('home', '0005_remove_onderzoeken_onderzoek_id_onderzoeken_id'),
    ]

    operations = [
    ]
