# Generated by Django 5.0.2 on 2024-03-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_beperkingen_beperkingenervaringsdeskundigen"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organisaties",
            fields=[
                ("organisatie_id", models.AutoField(primary_key=True, serialize=False)),
                ("voornaam", models.TextField(blank=True, null=True)),
                ("achternaam", models.TextField(blank=True, null=True)),
                ("kvk", models.TextField(blank=True, db_column="KVK", null=True)),
                ("website", models.TextField(blank=True, null=True)),
                ("beschrijving", models.TextField(blank=True, null=True)),
                ("contact_persoon", models.TextField(blank=True, null=True)),
                ("email", models.TextField(blank=True, null=True)),
                ("telefoonnummer", models.IntegerField(blank=True, null=True)),
                ("api_key", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("type", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "Organisaties",
                "managed": False,
            },
        ),
    ]
