# Generated by Django 4.2.10 on 2024-02-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ervaringsdeskundige', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ervaringsdeskundige',
            name='voorkeur_benadering',
            field=models.CharField(max_length=100),
        ),
    ]
