# Generated by Django 4.2.10 on 2024-02-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ervaringsdeskundige', '0002_alter_ervaringsdeskundige_voorkeur_benadering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ervaringsdeskundige',
            name='internet_onderzoek',
        ),
        migrations.RemoveField(
            model_name='ervaringsdeskundige',
            name='locatie_onderzoek',
        ),
        migrations.RemoveField(
            model_name='ervaringsdeskundige',
            name='telefonisch_onderzoek',
        ),
        migrations.RemoveField(
            model_name='ervaringsdeskundige',
            name='wachtwoord',
        ),
        migrations.AddField(
            model_name='ervaringsdeskundige',
            name='type_onderzoek',
            field=models.CharField(choices=[('Telefonisch Onderzoek', 'Telefonisch Onderzoek'), ('Online Onderzoek', 'Online Onderzoek'), ('Op locatie', 'Onderzoek op locatie')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ervaringsdeskundige',
            name='bijzonderheden',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ervaringsdeskundige',
            name='bijzonderheden_beschikbaarheid',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ervaringsdeskundige',
            name='email_voogd',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ervaringsdeskundige',
            name='voorkeur_benadering',
            field=models.CharField(choices=[('Internet', 'Via Internet'), ('Telefonisch', 'Telefonisch'), ('Locatie', 'Op locatie')], max_length=20),
        ),
    ]
