# Generated by Django 4.2.10 on 2024-02-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ervaringsdeskundige', '0003_remove_ervaringsdeskundige_internet_onderzoek_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ervaringsdeskundige',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ervaringsdeskundige',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ervaringsdeskundige',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
