# Generated by Django 4.2.10 on 2024-02-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ervaringsdeskundige', '0004_remove_ervaringsdeskundige_achternaam_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ervaringsdeskundige',
            old_name='email_voogd',
            new_name='email_voogd_of_toezichthouder',
        ),
        migrations.RenameField(
            model_name='ervaringsdeskundige',
            old_name='geboorte_datum',
            new_name='geboortedatum',
        ),
        migrations.RenameField(
            model_name='ervaringsdeskundige',
            old_name='achternaam_voogd',
            new_name='naam_voogd_of_toezichthouder',
        ),
        migrations.RenameField(
            model_name='ervaringsdeskundige',
            old_name='voogd',
            new_name='telefoonnummer',
        ),
        migrations.RenameField(
            model_name='ervaringsdeskundige',
            old_name='voornaam_voogd',
            new_name='telefoonnummer_voogd_of_toezichthouder',
        ),
        migrations.AddField(
            model_name='ervaringsdeskundige',
            name='toezichthouder',
            field=models.BooleanField(default=False, verbose_name='Toezichthouder'),
        ),
        migrations.AddField(
            model_name='ervaringsdeskundige',
            name='type_beperking',
            field=models.CharField(choices=[('auditief', 'Auditieve beperkingen'), ('visueel', 'Visuele beperkingen'), ('motorisch', 'Motorische / lichamelijke beperkingen'), ('cognitief', 'Cognitieve / neurologische beperkingen')], default='', max_length=100, verbose_name='Type beperking'),
        ),
        migrations.AlterField(
            model_name='ervaringsdeskundige',
            name='bijzonderheden',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ervaringsdeskundige',
            name='gebruikte_hulpmiddelen',
            field=models.TextField(max_length=200),
        ),
    ]
