# Generated by Django 4.2.10 on 2024-02-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ervaringsdeskundige', '0005_rename_email_voogd_ervaringsdeskundige_email_voogd_of_toezichthouder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ervaringsdeskundige',
            name='achternaam',
        ),
        migrations.RemoveField(
            model_name='ervaringsdeskundige',
            name='gebruikersnaam',
        ),
        migrations.RemoveField(
            model_name='ervaringsdeskundige',
            name='voornaam',
        ),
        migrations.AlterField(
            model_name='ervaringsdeskundige',
            name='bijzonderheden_beschikbaarheid',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
