# Generated by Django 4.2.9 on 2024-02-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ervaringsdeskundige', '0007_beperkingenervaringsdeskundigen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='goedegekeurd_door',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
