# Generated by Django 4.2.9 on 2024-02-29 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ervaringsdeskundige', '0008_alter_user_goedegekeurd_door'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toezichthouders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ervaringsdeskundige', models.IntegerField(blank=True, null=True)),
                ('voornaam_1', models.TextField()),
                ('achternaam_1', models.TextField()),
                ('telefoonnummer_1', models.TextField()),
                ('voornaam_2', models.TextField(blank=True, null=True)),
                ('achternaam_2', models.TextField(blank=True, null=True)),
                ('telefoonnummer_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Toezichthouders',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='toezichthouder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_toezichthouders', to='ervaringsdeskundige.toezichthouders'),
        ),
    ]
