# Generated by Django 5.0.2 on 2024-03-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ervaringsdeskundige", "0009_toezichthouders_alter_user_toezichthouder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(default=1, max_length=10),
        ),
    ]
